### ISSUE TITLE
rtl

### ISSUE THREAD

**Issue by w3cj** [CodingGarden/listd#11]

**Comment by omar2205** [comment]
https://gist.github.com/omar2205/d55d8ff748192f9685431a688beb5dc1

https://www.npmjs.com/package/tailwindcss-rtl

**Comment by Alileus** [comment]
try 
```css
main:lang(ar),
nav:lang(ar),
section:lang(ar) {
  direction: rtl;
}
````

and add `lang="ar"` in the div you want to rtl
